name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZjQ1OGM5ZTUtYTdhNi00ZTNmLWFiYzItNGZkZjIwZDJlNTlkIiwidGVuYW50X2lkIjoiYTZkMWIxMjhhMWVjZmRkNDRmOTIzZTU3Y2NjMjYxNGZmZTQ2ZDQyMDMzYmE1MWYyNTVhNTc0MWRlYjQ4M2I2MSIsImludGVybmFsX3NlY3JldCI6ImFlMzlmYTQ2LTM1MGMtNDBkZC1hMGQ2LWU1YjFiNWU4MmI3OSJ9.oRrmfo1_uuz6Dj1sXWF68BL8rxFcEP1E4UScmtEc0xA"
JWT_SECRET= "DhruvP"

